services:

  app:
    build: .
    container_name: rag-app

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - redis

    volumes:
      - ./chroma_db:/app/chroma_db
      - ./uploads:/app/uploads
      - ./users.db:/app/users.db

  redis:
    image: redis:7

    container_name: rag-redis

    ports:
      - "6379:6379"

  postgres:
    image: postgres:17
    container_name: rag-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docchat_ai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
